include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    parameter_assignments: error
    argument_type_not_assignable: ignore
    file_names: ignore
linter:
  rules:
    parameter_assignments: true
